language: python
python:
    - 3.4
    - 3.5
    - 3.6
env:
    - DJANGO_SETTINGS_MODULE="cie.settings.development"
install: pip install poetry && poetry install
script: pytest
after_success: coveralls
